Функция/гагина к/развитие светофор
ksenia-gagina/Traffic_lights pull request #1
Opened 2024-11-06 07:57 UTC by ksenia-gagina

2024-11-06 10:59 UTC, V1taS requested changes

2024-11-06 10:59 UTC, V1taS commented on Trafficlights/View.Controller.swift
> +//  View.Controller.swift
Почему файл назван View.Controller?

2024-11-06 10:59 UTC, V1taS commented on Trafficlights/View.Controller.swift
> +
Убрать лишний пробел

2024-11-06 10:59 UTC, V1taS commented on Trafficlights/View.Controller.swift
> +    {$0.translatesAutoresizingMaskIntoConstraints = false
Где фигурные скобки ставим пробелы { $0 }

2024-11-06 10:59 UTC, V1taS commented on Trafficlights/View.Controller.swift
> +     trafficLightStartButton].forEach {$0.translatesAutoresizingMaskIntoConstraints = false
Где фигурные скобки ставим пробелы { $0 } 

Если ты пишешь так {
  То все содержимое внутри должно находится
}

2024-11-06 10:59 UTC, V1taS commented on Trafficlights/View.Controller.swift
> +
Лишний отступ

2024-11-06 10:59 UTC, V1taS commented on Trafficlights/View.Controller.swift
> +    redCircleView.backgroundColor = .red.withAlphaComponent(0.5)
0.5 - вынести в константы

2024-11-06 10:59 UTC, V1taS commented on Trafficlights/View.Controller.swift
> +    yellowCircleView.backgroundColor = .yellow.withAlphaComponent(0.5)
0.5 - вынести в константы

2024-11-06 10:59 UTC, V1taS commented on Trafficlights/View.Controller.swift
> +    greenCircleView.backgroundColor = .green.withAlphaComponent(0.5)
0.5 - вынести в константы

2024-11-06 10:59 UTC, V1taS commented on Trafficlights/View.Controller.swift
> +    trafficLightType = newTrafficLightState  // сохранили новое значение
// сохранили новое значение - удалить лишний коммент

2024-11-06 10:59 UTC, V1taS commented on Trafficlights/View.Controller.swift
> +      yellowCircleView.backgroundColor = .yellow.withAlphaComponent(0.5)
0.5 - вынести в константы

2024-11-06 10:59 UTC, V1taS commented on Trafficlights/View.Controller.swift
> +      greenCircleView.backgroundColor = .green.withAlphaComponent(0.5)
0.5 - вынести в константы

2024-11-06 10:59 UTC, V1taS commented on Trafficlights/View.Controller.swift
> +      greenCircleView.backgroundColor = .green.withAlphaComponent(0.5)
0.5 - вынести в константы

2024-11-06 10:59 UTC, V1taS commented on Trafficlights/View.Controller.swift
> +      redCircleView.backgroundColor = .red.withAlphaComponent(0.5)
0.5 - вынести в константы

2024-11-06 10:59 UTC, V1taS commented on Trafficlights/View.Controller.swift
> +      yellowCircleView.backgroundColor = .yellow.withAlphaComponent(0.5)
0.5 - вынести в константы

2024-11-06 10:59 UTC, V1taS commented on Trafficlights/View.Controller.swift
> +      redCircleView.backgroundColor = .red.withAlphaComponent(0.5)
0.5 - вынести в константы

2024-11-06 10:59 UTC, V1taS commented on Trafficlights/View.Controller.swift
> +//MARK: - Constants
Отступы
//MARK: - Constants
Отступы

2024-11-06 10:59 UTC, V1taS commented on Trafficlights/View.Controller.swift
> +  static let trafficLightHousingTop: CGFloat = 150
Если ты создаешь константу с отступом то в конце добавляй padding (отступ)
trafficLightHousingTopPadding

2024-11-06 10:59 UTC, V1taS commented on Trafficlights/ViewController.swift
> +final class ViewController: UIViewController {
А зачем тебе второй ViewController ?

2024-11-06 10:59 UTC, V1taS commented on Trafficlights/ViewController.swift
> +final class ViewController: UIViewController {
Тебе надо удалить этот файл

2024-11-06 20:05 UTC, ksenia-gagina commented on Trafficlights/View.Controller.swift
> +
Убрала отступ

2024-11-06 20:05 UTC, ksenia-gagina commented on Trafficlights/View.Controller.swift
> +    {$0.translatesAutoresizingMaskIntoConstraints = false
Исправила

2024-11-06 20:06 UTC, ksenia-gagina commented on Trafficlights/View.Controller.swift
> +//  View.Controller.swift
Не получилось изменить название

2024-11-06 20:06 UTC, ksenia-gagina commented on Trafficlights/View.Controller.swift
> +     trafficLightStartButton].forEach {$0.translatesAutoresizingMaskIntoConstraints = false
Поправила

2024-11-06 20:06 UTC, ksenia-gagina commented on Trafficlights/View.Controller.swift
> +
Исправила

2024-11-06 20:06 UTC, ksenia-gagina commented on Trafficlights/View.Controller.swift
> +    redCircleView.backgroundColor = .red.withAlphaComponent(0.5)
Вынесла

2024-11-06 20:06 UTC, ksenia-gagina commented on Trafficlights/View.Controller.swift
> +    yellowCircleView.backgroundColor = .yellow.withAlphaComponent(0.5)
Вынесла

2024-11-06 20:06 UTC, ksenia-gagina commented on Trafficlights/View.Controller.swift
> +    greenCircleView.backgroundColor = .green.withAlphaComponent(0.5)
Вынесла

2024-11-06 20:07 UTC, ksenia-gagina commented on Trafficlights/View.Controller.swift
> +    trafficLightType = newTrafficLightState  // сохранили новое значение
Удалила коммент

2024-11-06 20:07 UTC, ksenia-gagina commented on Trafficlights/View.Controller.swift
> +      yellowCircleView.backgroundColor = .yellow.withAlphaComponent(0.5)
Вынесла

2024-11-06 20:07 UTC, ksenia-gagina commented on Trafficlights/View.Controller.swift
> +      greenCircleView.backgroundColor = .green.withAlphaComponent(0.5)
Вынесла

2024-11-06 20:07 UTC, ksenia-gagina commented on Trafficlights/View.Controller.swift
> +      greenCircleView.backgroundColor = .green.withAlphaComponent(0.5)
Вынесла

2024-11-06 20:07 UTC, ksenia-gagina commented on Trafficlights/View.Controller.swift
> +      redCircleView.backgroundColor = .red.withAlphaComponent(0.5)
Вынесла

2024-11-06 20:07 UTC, ksenia-gagina commented on Trafficlights/View.Controller.swift
> +      yellowCircleView.backgroundColor = .yellow.withAlphaComponent(0.5)
Вынесла

2024-11-06 20:07 UTC, ksenia-gagina commented on Trafficlights/View.Controller.swift
> +      redCircleView.backgroundColor = .red.withAlphaComponent(0.5)
Вынесла

2024-11-06 20:07 UTC, ksenia-gagina commented on Trafficlights/View.Controller.swift
> +//MARK: - Constants
Поставила отступы

2024-11-06 20:08 UTC, ksenia-gagina commented on Trafficlights/View.Controller.swift
> +  static let trafficLightHousingTop: CGFloat = 150
Добавила padding к названию константы

2024-11-06 20:08 UTC, ksenia-gagina commented on Trafficlights/ViewController.swift
> +final class ViewController: UIViewController {
Удалила ViewController

2024-11-07 08:37 UTC, V1taS requested changes

2024-11-07 08:37 UTC, V1taS commented on Trafficlights/View.Controller.swift
> +  static let transparencyCircle:CGFloat = 0.5
transparencyCircle:CGFloat - Слепилось

2024-11-07 17:32 UTC, merged